image: "srittau/wsgi-base:3.7"

services:
  - redis:latest

stages:
  - test
  - build
test:
  script:
    - pip3 install --quiet -r requirements.txt
    - pip3 install https://github.com/kpu/kenlm/archive/master.zip
    - python3 ./worker/simpleServer.py &
    - python3 ./worker/simpleServer.py nlumdl1-gitlabci-wk2 &
    - python3 server.py &
    - cd ztest
    - python3 ab_test.py

build:
  stage: build
  image: "docker:stable"
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    DOCKER_HOST: 'tcp://docker:2375'
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:stable-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - |
      docker image pull "$CI_APPLICATION_REPOSITORY:$CI_COMMIT_BEFORE_SHA" || \
      docker image pull "$CI_APPLICATION_REPOSITORY:latest" || \
      true
    - |
      docker build \
        --cache-from "$CI_APPLICATION_REPOSITORY:$CI_COMMIT_BEFORE_SHA" \
        --cache-from "$CI_APPLICATION_REPOSITORY:latest" \
        --tag "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" \
        --tag "$CI_APPLICATION_REPOSITORY:latest" .
    - docker push "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
    - docker push "$CI_APPLICATION_REPOSITORY:latest"
  only:
    - branches
    - tags
